exports.seed = function (knex) {
    // Deletes ALL existing entries
    return knex("language")
        .del()
        .then(function () {
            // Inserts seed entries
            return knex("language").insert([
                {
                    code: "af",
                    name: "Afrikaans",
                    native_name: "Afrikaans",
                    is_active: true,
                },
                {
                    code: "sq",
                    name: "Albanian",
                    native_name: "Shqip",
                    is_active: true,
                },
                {
                    code: "ar",
                    name: "Arabic",
                    native_name: "العربية",
                    is_active: true,
                },
                {
                    code: "az",
                    name: "Azerbaijani",
                    native_name: "Azərbaycan",
                    is_active: true,
                },
                {
                    code: "bn",
                    name: "Bengali",
                    native_name: "বাংলা",
                    is_active: true,
                },
                {
                    code: "bg",
                    name: "Bulgarian",
                    native_name: "Български",
                    is_active: true,
                },
                {
                    code: "ca",
                    name: "Catalan",
                    native_name: "Català",
                    is_active: true,
                },
                {
                    code: "zh_CN",
                    name: "Chinese (CHN)",
                    native_name: "中文 (中国)",
                    is_active: true,
                },
                {
                    code: "zh_HK",
                    name: "Chinese (HKG)",
                    native_name: "中文 (香港)",
                    is_active: true,
                },
                {
                    code: "zh_TW",
                    name: "Chinese (TAI)",
                    native_name: "中文 (台灣)",
                    is_active: true,
                },
                {
                    code: "hr",
                    name: "Croatian",
                    native_name: "Hrvatski",
                    is_active: true,
                },
                {
                    code: "cs",
                    name: "Czech",
                    native_name: "Čeština",
                    is_active: true,
                },
                {
                    code: "da",
                    name: "Danish",
                    native_name: "Dansk",
                    is_active: true,
                },
                {
                    code: "nl",
                    name: "Dutch",
                    native_name: "Nederlands",
                    is_active: true,
                },
                {
                    code: "en",
                    name: "English",
                    native_name: "English",
                    is_active: true,
                },
                {
                    code: "en_GB",
                    name: "English (UK)",
                    native_name: "English (UK)",
                    is_active: true,
                },
                {
                    code: "en_US",
                    name: "English (US)",
                    native_name: "English (US)",
                    is_active: true,
                },
                {
                    code: "et",
                    name: "Estonian",
                    native_name: "Eesti",
                    is_active: true,
                },
                {
                    code: "fil",
                    name: "Filipino",
                    native_name: "Filipino",
                    is_active: true,
                },
                {
                    code: "fi",
                    name: "Finnish",
                    native_name: "Suomi",
                    is_active: true,
                },
                {
                    code: "fr",
                    name: "French",
                    native_name: "Français",
                    is_active: true,
                },
                {
                    code: "ka",
                    name: "Georgian",
                    native_name: "ქართული",
                    is_active: true,
                },
                {
                    code: "de",
                    name: "German",
                    native_name: "Deutsch",
                    is_active: true,
                },
                {
                    code: "el",
                    name: "Greek",
                    native_name: "Ελληνικά",
                    is_active: true,
                },
                {
                    code: "gu",
                    name: "Gujarati",
                    native_name: "ગુજરાતી",
                    is_active: true,
                },
                {
                    code: "ha",
                    name: "Hausa",
                    native_name: "Hausa",
                    is_active: true,
                },
                {
                    code: "he",
                    name: "Hebrew",
                    native_name: "עברית",
                    is_active: true,
                },
                {
                    code: "hi",
                    name: "Hindi",
                    native_name: "हिन्दी",
                    is_active: true,
                },
                {
                    code: "hu",
                    name: "Hungarian",
                    native_name: "Magyar",
                    is_active: true,
                },
                {
                    code: "id",
                    name: "Indonesian",
                    native_name: "Bahasa Indonesia",
                    is_active: true,
                },
                {
                    code: "ga",
                    name: "Irish",
                    native_name: "Gaeilge",
                    is_active: true,
                },
                {
                    code: "it",
                    name: "Italian",
                    native_name: "Italiano",
                    is_active: true,
                },
                {
                    code: "ja",
                    name: "Japanese",
                    native_name: "日本語",
                    is_active: true,
                },
                {
                    code: "kn",
                    name: "Kannada",
                    native_name: "ಕನ್ನಡ",
                    is_active: true,
                },
                {
                    code: "kk",
                    name: "Kazakh",
                    native_name: "Қазақ",
                    is_active: true,
                },
                {
                    code: "rw_RW",
                    name: "Kinyarwanda",
                    native_name: "Kinyarwanda",
                    is_active: true,
                },
                {
                    code: "ko",
                    name: "Korean",
                    native_name: "한국어",
                    is_active: true,
                },
                {
                    code: "ky_KG",
                    name: "Kyrgyz (Kyrgyzstan)",
                    native_name: "Кыргызча",
                    is_active: true,
                },
                {
                    code: "lo",
                    name: "Lao",
                    native_name: "ລາວ",
                    is_active: true,
                },
                {
                    code: "lv",
                    name: "Latvian",
                    native_name: "Latviešu",
                    is_active: true,
                },
                {
                    code: "lt",
                    name: "Lithuanian",
                    native_name: "Lietuvių",
                    is_active: true,
                },
                {
                    code: "mk",
                    name: "Macedonian",
                    native_name: "Македонски",
                    is_active: true,
                },
                {
                    code: "ms",
                    name: "Malay",
                    native_name: "Bahasa Melayu",
                    is_active: true,
                },
                {
                    code: "ml",
                    name: "Malayalam",
                    native_name: "മലയാളം",
                    is_active: true,
                },
                {
                    code: "mr",
                    name: "Marathi",
                    native_name: "मराठी",
                    is_active: true,
                },
                {
                    code: "nb",
                    name: "Norwegian",
                    native_name: "Norsk Bokmål",
                    is_active: true,
                },
                {
                    code: "fa",
                    name: "Persian",
                    native_name: "فارسی",
                    is_active: true,
                },
                {
                    code: "pl",
                    name: "Polish",
                    native_name: "Polski",
                    is_active: true,
                },
                {
                    code: "pt_BR",
                    name: "Portuguese (BR)",
                    native_name: "Português (Brasil)",
                    is_active: true,
                },
                {
                    code: "pt_PT",
                    name: "Portuguese (POR)",
                    native_name: "Português (Portugal)",
                    is_active: true,
                },
                {
                    code: "pa",
                    name: "Punjabi",
                    native_name: "ਪੰਜਾਬੀ",
                    is_active: true,
                },
                {
                    code: "ro",
                    name: "Romanian",
                    native_name: "Română",
                    is_active: true,
                },
                {
                    code: "ru",
                    name: "Russian",
                    native_name: "Русский",
                    is_active: true,
                },
                {
                    code: "sr",
                    name: "Serbian",
                    native_name: "Српски",
                    is_active: true,
                },
                {
                    code: "sk",
                    name: "Slovak",
                    native_name: "Slovenčina",
                    is_active: true,
                },
                {
                    code: "sl",
                    name: "Slovenian",
                    native_name: "Slovenščina",
                    is_active: true,
                },
                {
                    code: "es",
                    name: "Spanish",
                    native_name: "Español",
                    is_active: true,
                },
                {
                    code: "es_AR",
                    name: "Spanish (ARG)",
                    native_name: "Español (Argentina)",
                    is_active: true,
                },
                {
                    code: "es_ES",
                    name: "Spanish (SPA)",
                    native_name: "Español (España)",
                    is_active: true,
                },
                {
                    code: "es_MX",
                    name: "Spanish (MEX)",
                    native_name: "Español (México)",
                    is_active: true,
                },
                {
                    code: "sw",
                    name: "Swahili",
                    native_name: "Kiswahili",
                    is_active: true,
                },
                {
                    code: "sv",
                    name: "Swedish",
                    native_name: "Svenska",
                    is_active: true,
                },
                {
                    code: "ta",
                    name: "Tamil",
                    native_name: "தமிழ்",
                    is_active: true,
                },
                {
                    code: "te",
                    name: "Telugu",
                    native_name: "తెలుగు",
                    is_active: true,
                },
                {
                    code: "th",
                    name: "Thai",
                    native_name: "ไทย",
                    is_active: true,
                },
                {
                    code: "tr",
                    name: "Turkish",
                    native_name: "Türkçe",
                    is_active: true,
                },
                {
                    code: "uk",
                    name: "Ukrainian",
                    native_name: "Українська",
                    is_active: true,
                },
                {
                    code: "ur",
                    name: "Urdu",
                    native_name: "اردو",
                    is_active: true,
                },
                {
                    code: "uz",
                    name: "Uzbek",
                    native_name: "O'zbek",
                    is_active: true,
                },
                {
                    code: "vi",
                    name: "Vietnamese",
                    native_name: "Tiếng Việt",
                    is_active: true,
                },
                {
                    code: "zu",
                    name: "Zulu",
                    native_name: "isiZulu",
                    is_active: true,
                },
            ]);
        });
};
